baseURL = "https://douarenn.fr/"
languageCode = "en-us"
title = "Douarenn"
theme = "douarenn"
[params]
 footer = "Déconnexion au coeur des Monts d'Arrée."
[params.font]
  url = "https://use.typekit.net/inf6jer.css"
[params.plausible]
  domain = "douarenn.fr"
[params.social]
  instagram = "douarenn"
  email = "bonjour@douarenn.fr"
  domain = "douarenn.fr"
[security.exec]
 osEnv =  ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$','(?i)^ASDF', '^HOME$']
